## Sample Kubernetes deployment
#
# This manifest defines a simple nginx deployment and service.  It
# serves as an example application that can be deployed via Argo CD.

apiVersion: v1
kind: Namespace
metadata:
  name: sample

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: sample
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: sample
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80